import {useEffect,useState} from 'react';
import {Users,ArrowRight} from 'lucide-react';
export function Login({onSuccess}:{onSuccess:()=>void}){
 const [setup,setSetup]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/auth/status').then(async r=>{if(!r.ok)throw Error();const d=await r.json() as {needsSetup:boolean};setSetup(d.needsSetup);setReady(true);}).catch(()=>setError('Não foi possível verificar o acesso. Atualize a página.'));},[]);
 return <section className="login panel"><div className="brand-mark"><Users size={30}/></div><h2>{setup?'Configure sua equipe':'Bem-vindo ao SIMAS'}</h2><p>{setup?'Crie a conta de administrador para começar.':'Entre com seu e-mail e senha para acessar a escala.'}</p>{error&&<div className="alert error" role="alert">{error}</div>}{ready&&<form className="login-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/'+(setup?'setup':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);onSuccess();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{setup&&<><label className="field"><span>Código de instalação</span><input name="token" type="password" required autoComplete="off" placeholder="Código definido na hospedagem"/></label><label className="field"><span>Seu nome</span><input name="name" required minLength={2} autoComplete="name"/></label></>}<label className="field"><span>E-mail</span><input name="email" type="email" required autoComplete="username" placeholder="voce@empresa.com.br"/></label><label className="field"><span>Senha</span><input name="password" type="password" required minLength={12} maxLength={128} autoComplete={setup?'new-password':'current-password'} placeholder={setup?'Pelo menos 12 caracteres':'Sua senha'}/></label><button className="button primary" disabled={busy} type="submit">{busy?'Aguarde…':setup?'Criar administrador':'Entrar'}<ArrowRight size={17}/></button></form>}<small>{setup?'O código impede que terceiros assumam a primeira conta.':'Precisa de acesso ou esqueceu a senha? Procure o administrador da sua equipe.'}</small></section>;
}
export function UserAccountForm({onSuccess}:{onSuccess:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);onSuccess();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{error&&<div role="alert" className="alert error">{error}</div>}<label className="field"><span>Nome</span><input name="name" minLength={2} required/></label><label className="field"><span>E-mail</span><input name="email" type="email" required/></label><label className="field"><span>Senha inicial</span><input name="password" type="password" minLength={12} maxLength={128} required autoComplete="new-password" placeholder="Pelo menos 12 caracteres"/></label><label className="field"><span>Perfil</span><select name="role"><option value="viewer">Consulta</option><option value="admin">Administrador</option></select></label><p className="form-hint">Compartilhe o acesso diretamente com a pessoa. O SIMAS não envia senhas por e-mail.</p><div className="modal-footer"><button className="button primary" disabled={busy}>{busy?'Salvando…':'Criar acesso'}</button></div></form>;}
export function PasswordForm({id,onSuccess}:{id:string;onSuccess:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <form onSubmit={async e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');setBusy(true);try{const r=await fetch('/api/users/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,password})});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);onSuccess();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{error&&<div className="alert error">{error}</div>}<label className="field"><span>Nova senha</span><input name="password" type="password" minLength={12} maxLength={128} required autoComplete="new-password"/></label><p className="form-hint">Os acessos abertos desta conta serão encerrados.</p><div className="modal-footer"><button className="button primary" disabled={busy}>Salvar nova senha</button></div></form>;}
